apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vs2z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vs2z
    app.kubernetes.io/part-of: tkrw-pr714-0075-0060-app
  name: devfile-sample-vs2z
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vs2z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vs2z
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0060-tenant/tkrw-pr714-0075-0060-app/devfile-sample-vs2z@sha256:761abfe1ff763c9bb012559b8f74aa05bc7bd585bc94a48365c0a8c7374669ad
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
